"""channels, sessions, highlights, clips

Revision ID: 3de5f631af9c
Revises: 
Create Date: 2026-09-29 10:58:40.656326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3de5f631af9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('detector_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('platform', 'login', name=op.f('uq_channels_platform'))
    )
    op.create_table('stream_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('live', 'ended', 'interrupted', name='sessionstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_stream_sessions_channel_id_channels'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_sessions'))
    )
    op.create_index('uq_stream_sessions_one_live', 'stream_sessions', ['channel_id'], unique=True, postgresql_where=sa.text("status = 'live'"))
    op.create_table('highlights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('peak_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['stream_sessions.id'], name=op.f('fk_highlights_session_id_stream_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_highlights'))
    )
    op.create_index(op.f('ix_highlights_session_id'), 'highlights', ['session_id'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('highlight_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('auto', 'manual', name='clipsource', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='clipstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=256), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=256), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('has_gap', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_clips_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], name=op.f('fk_clips_highlight_id_highlights'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['stream_sessions.id'], name=op.f('fk_clips_session_id_stream_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clips')),
    sa.UniqueConstraint('highlight_id', name=op.f('uq_clips_highlight_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    op.drop_index(op.f('ix_highlights_session_id'), table_name='highlights')
    op.drop_table('highlights')
    op.drop_index('uq_stream_sessions_one_live', table_name='stream_sessions', postgresql_where=sa.text("status = 'live'"))
    op.drop_table('stream_sessions')
    op.drop_table('channels')
    # ### end Alembic commands ###
