"""channels, sessions, highlights, clips

Revision ID: 94f7264acf83
Revises: 3de5f631af9c
Create Date: 2026-09-29 11:28:12.440019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f7264acf83'
down_revision: Union[str, Sequence[str], None] = '3de5f631af9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_channels_platform'), 'channels', type_='unique')
    op.create_unique_constraint(op.f('uq_channels_platform_login'), 'channels', ['platform', 'login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_channels_platform_login'), 'channels', type_='unique')
    op.create_unique_constraint(op.f('uq_channels_platform'), 'channels', ['platform', 'login'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
